### ISSUE TITLE
Assignment submission integration with GitHub (or some other source control)

### ISSUE THREAD

**Issue by ikemtz** [blackboard/blackboard.github.io#14]
I'm a CIS student and have been using the Blackboard platform for two years now at two different schools.  I find it frustrating that Students at these schools have to submit there work in Zip files and other means when in reality CIS students should be learning how to use a source control repository.

In an effort to improve the chances of students being able to get a job after graduation, I am meeting with deans and program directors at my current school to revamp the curriculum.  The lack of source control acumen in most schools is an issue that is at the top of my list.

I noticed that GitHub classroom has support for other learning management systems, and Blackboard is soon coming.  Do we have an ETA on this?  

https://classroom.github.com/help/connect-to-lms

**Comment by daveyherrera** [comment]
Hello there,

Unfortunately we do not have an ETA for this to be release, please feel free to use our forums at community.blackboard.com in order to get more information on this.

Sorry we are unable to provide relevant information about this.
