### ISSUE TITLE
Try to merge pulls and getting error message.

### ISSUE THREAD

**Issue by mark-b-kauffman** [blackboard/blackboard.github.io#40]
The page build failed for the `master` branch with the following error:

Page build failed. For more information, see https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#troubleshooting-build-errors

Thing is the latest merge is what we already have published.

**Comment by shurrey** [comment]
Had to delete and regenerate the Gemfile.lock file, and also update a dependency. Should be back up and running.
