### ISSUE TITLE
Question on REST Integration

### ISSUE THREAD

**Issue by enigmablue** [blackboard/blackboard.github.io#7]
Hi i have a mobile and web app, and i am working with a few schools to integrate into their blackboard. In the mean-time, i have also setup my own Blackboard Learn Instance via AWS.

I was looking into the LTI and REST API and is quite confused. I think those are bringing apps into Blackboard instead. Whilst here i am requiring to retrieve data from the Blackboard instance.

Could you share where i can look? 

--UPDATE-- OH I think its in web services perhaps, found a tab..

**Comment by shurrey** [comment]
This sitemap should help you find what you are looking for. Under Learn, you will see a REST section that contains all the REST documentation. Under standards, you will see LTI.

https://docs.blackboard.com/sitemap.html
